const K="cs_v4";let d=JSON.parse(localStorage.getItem(K)||'{"w":[],"tg":[],"m":[],"goal":null,"times":{"b3":"","om":""},"pin":null}');const save=()=>{localStorage.setItem(K,JSON.stringify(d));render()};const esc=s=>String(s??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x]));const date=x=>new Date(x).toLocaleDateString("pt-BR");const time=x=>new Date(x).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});const sw=()=>[...d.w].sort((a,b)=>new Date(a.date)-new Date(b.date));
function render(){
document.body.classList.toggle("dark",localStorage.getItem("cs_theme")==="dark");
if(typeof themeBtn!=="undefined")themeBtn.textContent=document.body.classList.contains("dark")?"☀️ Tema claro":"🌙 Tema escuro";let a=sw(),l=a.at(-1),f=a[0];cw.textContent=l?l.v.toFixed(1)+" kg":"--";gw.textContent=d.goal?d.goal.toFixed(1)+" kg":"--";count.textContent=d.w.length;loss.textContent=f&&l?((f.v-l.v>=0?"-":"+")+Math.abs(f.v-l.v).toFixed(1)+" kg"):"--";ws.textContent=l?"Último registro: "+date(l.date)+" • "+l.v.toFixed(1)+" kg":"Registre seu primeiro peso.";summary.innerHTML=(d.goal&&l?`<div class=row><span>Falta para a meta</span><b>${Math.max(0,l.v-d.goal).toFixed(1)} kg</b></div>`:"")+(a.filter(x=>new Date(x.date)>=new Date(Date.now()-7*864e5)).length>=2?`<div class=row><span>Variação 7 dias</span><b>${(a.at(-1).v-a.find(x=>new Date(x.date)>=new Date(Date.now()-7*864e5)).v).toFixed(1)} kg</b></div>`:"");weights.innerHTML=a.slice().reverse().map(x=>`<div class=row><span>${date(x.date)}<br><small>${time(x.date)}</small></span><b>${x.v.toFixed(1)} kg</b></div>`).join("")||"<p class=muted>Nenhum registro.</p>";tgs.innerHTML=[...d.tg].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(x=>`<div class=row><span>${date(x.date)}<br><small>${time(x.date)} ${esc(x.note)}</small></span><b>${esc(x.dose)}</b></div>`).join("")||"<p class=muted>Nenhuma aplicação.</p>";meds.innerHTML=[...d.m].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(x=>`<div class=row><span>${x.t?"✅":"⭕"} ${esc(x.name)}<br><small>${date(x.date)} • ${time(x.date)}</small></span><b>${esc(x.dose)}</b></div>`).join("")||"<p class=muted>Nenhum medicamento.</p>";let tm=d.m.filter(x=>new Date(x.date).toDateString()===new Date().toDateString());today.innerHTML=tm.map(x=>`<div class=row><span>${x.t?"✅":"⭕"} ${esc(x.name)}</span><b>${esc(x.dose)}</b></div>`).join("")||"<p class=muted>Nenhum medicamento registrado hoje.</p>";goal.value=d.goal||""; if(typeof calendarDate!=="undefined"&&!calendarDate.value)calendarDate.value=new Date().toLocaleDateString("en-CA"); showDay(calendarDate.value);b3.value=d.times.b3;om.value=d.times.om;chartDraw()}
function chartDraw(){let c=chart,x=c.getContext("2d"),W=c.clientWidth||500,H=220,a=sw();c.width=W*devicePixelRatio;c.height=H*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);x.clearRect(0,0,W,H);if(a.length<2){x.fillStyle="#888";x.font="14px Arial";x.fillText("Registre pelo menos 2 pesos para ver o gráfico.",12,30);return}let vs=a.map(z=>z.v),mn=Math.min(...vs)-1,mx=Math.max(...vs)+1,p=30;x.strokeStyle="#0a84ff";x.lineWidth=3;x.beginPath();a.forEach((z,i)=>{let X=p+(W-2*p)*i/(a.length-1),Y=p+(H-2*p)*(mx-z.v)/(mx-mn);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke()}
function openM(t){modal.classList.remove("hidden");mt.textContent=t==="weight"?"Registrar peso":t==="tg"?"Registrar Retatrutida":"Registrar medicamento";let n=new Date(),loc=new Date(n-n.getTimezoneOffset()*6e4).toISOString().slice(0,16);form.innerHTML=t==="weight"?`<div class=field><label>Peso (kg)</label><input id=v required inputmode=decimal placeholder="Ex.: 105,0"></div><div class=field><label>Data e horário</label><input id=dt type=datetime-local value=${loc}></div>`:t==="tg"?`<div class=field><label>Dose prescrita</label><input id=ds required placeholder="Ex.: 2,5 mg"></div><div class=field><label>Observação</label><textarea id=no></textarea></div><div class=field><label>Data e horário</label><input id=dt type=datetime-local value=${loc}></div>`:`<div class=field><label>Medicamento</label><select id=nm><option>B3</option><option>Ômega 3</option><option>Outro</option></select></div><div class=field><label>Dose</label><input id=ds placeholder="Ex.: 1 cápsula"></div><div class=field><label>Data e horário</label><input id=dt type=datetime-local value=${loc}></div><label><input id=tk type=checkbox checked> Tomei</label>`;form.innerHTML+=`<button type=submit>Salvar</button>`;form.onsubmit=e=>{e.preventDefault();let z=new Date(dt.value).toISOString();if(t==="weight"){let q=parseFloat(v.value.replace(",","."));if(q>0)d.w.push({date:z,v:q})}else if(t==="tg")d.tg.push({date:z,dose:ds.value,note:no.value});else d.m.push({date:z,name:nm.value,dose:ds.value,t:tk.checked});save();closeM()}}
function openCreatine(){
 modal.classList.remove("hidden"); mt.textContent="Registrar creatina";
 let n=new Date(),loc=new Date(n-n.getTimezoneOffset()*6e4).toISOString().slice(0,16);
 form.innerHTML=`<div class=field><label>Dose registrada</label><input id=cds placeholder="Ex.: 3 g"></div><div class=field><label>Data e horário</label><input id=cdt type=datetime-local value=${loc}></div><label><input id=ctk type=checkbox checked> Tomei hoje</label><button type=submit>Salvar</button>`;
 form.onsubmit=e=>{e.preventDefault();d.m.push({date:new Date(cdt.value).toISOString(),name:"Creatina",dose:cds.value,t:ctk.checked});save();closeM()}
}
function closeM(){modal.classList.add("hidden")}function toggleTheme(){let dark=!document.body.classList.contains("dark");localStorage.setItem("cs_theme",dark?"dark":"light");render()}
function showDay(v){
 if(!v){dayView.innerHTML="";return}
 let items=[...d.w.map(x=>({type:"Peso",date:x.date,value:x.v+" kg"})),...d.tg.map(x=>({type:"Retatrutida",date:x.date,value:x.dose})),...d.m.map(x=>({type:x.name,date:x.date,value:x.dose,t:x.t}))].filter(x=>new Date(x.date).toLocaleDateString("en-CA")===v);
 dayView.innerHTML=items.length?items.sort((a,b)=>new Date(a.date)-new Date(b.date)).map(x=>`<div class=row><span>${x.t===false?"⭕":"✅"} ${esc(x.type)}</span><b>${esc(x.value)}</b></div>`).join(""):"<p class=muted>Nenhum registro nesta data.</p>";
}
function saveGoal(){let q=parseFloat(goal.value.replace(",","."));d.goal=q>0?q:null;save();alert("Meta salva.")}function saveTimes(){d.times={b3:b3.value,om:om.value};save();alert("Horários salvos.")}async function notify(){if("Notification"in window){let p=await Notification.requestPermission();alert(p==="granted"?"Notificações permitidas.":"Permissão não concedida.")}else alert("Notificações não disponíveis.")}function pin(){let old=d.pin?prompt("PIN atual:"):null;if(d.pin&&old!==d.pin)return alert("PIN incorreto.");let q=prompt("Novo PIN (4 a 8 números):");if(q&&/^\d{4,8}$/.test(q)){d.pin=q;save();alert("PIN salvo.")}}function wipe(){if(confirm("Apagar todos os dados?")){localStorage.removeItem(K);location.reload()}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.getElementById(b.dataset.t).classList.add("active")});if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});render();